---
title: "Parámetros de interés"
author: "Irvin Rojas"
institute: "CIDE"
date: "2 de septiembre de 2021"
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{shapes, shadows,arrows}
output:
  xaringan::moon_reader:
    css: [default, "libs/cide.css", metropolis-fonts, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    seal: false
    chakra: "https://remarkjs.com/downloads/remark-latest.min.js"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["middle", "center"]
      ratio: "16:9"
      beforeInit: ["https://platform.twitter.com/widgets.js", "libs/cols_macro.js"]
      navigation:
        scroll: false


---
class: title-slide

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figures/")
library(tidyverse)
library(magick)
library(reticulate)
library(knitr)
library(kableExtra)

xfun::pkg_load2(c('base64enc', 'htmltools', 'mime'))
```

.title[
# Clase 6. Parámetros de interés 
]
.subtitle[
## Evaluación de Programas
]
.author[
### Irvin Rojas <br> [rojasirvin.com](https://www.rojasirvin.com/) <br> [<i class="fab fa-github"></i>](https://github.com/rojasirvin) [<i class="fab fa-twitter"></i>](https://twitter.com/RojasIrvin) [<i class="ai ai-google-scholar"></i>](https://scholar.google.com/citations?user=FUwdSTMAAAAJ&hl=en)
]

.affiliation[
### Centro de Investigación y Docencia Económicas <br> División de Economía
]

---
# Agenda

1. Definiremos parámetros clave en la literatura de efectos de tratamiento

---

class: inverse, middle, center

# Parámetros de interés de efectos de tratamiento

---

# Supuesto de independencia condicional

- En la sesión anterior vimos que el SIC nos dice que, condicional en $X_i$, los resultados potenciales son independientes del tratamiento

- Cuando el tratamiento se asigna de manera aleatoria y el diseño experimental se, el supuesto es válido

- Más aún, bajo asignación aleatoria, podemos hacer un supuesto aún más fuerte:

$$\{y_{0i},y_{1i}\perp D_i \}$$

---

# Efectos de tratamiento

- Vamos a definir dos medidas de efecto de tratamiento ampliamente usadas en la literatura

- Definamos el cambio en la variable de resultados de un individuo:

$$\Delta_i=y_{1i}-y_{0i}$$

**Efecto promedio del tratamiento** (ATE): se interpreta como la ganancia hipotética debido al tratamiento para un individuo seleccionado al azar en una población

- Este parámetro es de relevancia cuando pensamos en tratamientos de aplicación universal

- Matemáticamente:

$$ATE=E(\Delta)$$

- Con su correspondiente análogo muestral:
$$\hat{ATE}=\frac{1}{N}\sum_i^N\Delta_i$$

---

# Efectos de tratamiento

**Efecto promedio del tratamiento en los tratados** (ATET, TT, TOT)

- Como su nombre lo dice, este parámetro solo considera a los individuos que son efectivamente tratados

- Matemáticamente:
$$ATET=E(\Delta_i|D_i=1)$$

- Y su análogo muestral es:

$$\hat{ATET}=\frac{1}{N_T}\sum_i^{N_T}(\Delta_i|D_i=1)$$

---

# Efectos de tratamiento

- Heckman (1997) critica el uso del ATE pues pudiera ser irrelevante

- ¿Cuál es el ATE de PROGRESA, por ejemplo?

- La contracrítica es que siempre podemos restringir lo que es la *población* de interés

--

- Noten que el ATET también abre la puerta a casos en los que, aún cuando el tratamiento se asignó aleatoriamente en un grupo, no todos a los que se les asigna el tratamiento efectivamente lo reciben

--

- En ambos casos, no podemos estimar directamente los parámetros pues no observamos $\Delta_i$

- Sin embargo, ya vimos cómo, con una muestra de tratados y no tratados, podemos inferir el efecto del tratamiento, bajo algunos supuestos

- Nuestras afirmaciones siempre irán acompañadas de una *medida de incertidumbre* debido al error muestral

---
# Próxima sesión

- Veremos un ejemplo un tanto distinto: un proyecto a escala masiva

  - Banerjee, A., Duflo, E., Goldberg, N., Karlan, D., Osei, R., Parienté, W., Shapiro, J., Thuysbaert, B. & Udry, C. (2015). A multifaceted program causes lasting progress for the very poor: Evidence from six countries. *Science*, 348(6236), 1260799.

---

class: center, middle

Presentación creada usando el paquete [**xaringan**](https://github.com/yihui/xaringan) en R.

El *chakra* viene de [remark.js](https://remarkjs.com), [**knitr**](http://yihui.org/knitr), y [R Markdown](https://rmarkdown.rstudio.com).

Material de clase en versión preliminar.

**No reproducir, no distribuir, no citar.**


