---
title: "Respuestas a la tarea 4"
summary: " "
weight: 2
type: book
toc: false
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="instrucciones" class="section level2">
<h2>Instrucciones</h2>
<p>La tarea debe entregarse de manera individual, pero se recomienda ampliamente colaborar en grupos de estudio. Las secciones teóricas deben estar desarrolladas en un procesador de textos y enviadas en formato .docx o .pdf. Las secciones prácticas deberán contener archivos de código replicable y archivos de salida en R (o similares, en caso de usar otro software) para considerarse completas. Las tareas deben entregarse antes de la fecha límite a través de Teams. Puede crear una carpeta comprimida que contenga todos sus archivos y subir esta carpeta en Teams. Recuerde que en Teams debe asegurarse de que los archivos se han subido correctamente.</p>
<p>El archivo <em>basque.csv</em> contiene los datos empleados por Abadie y Gardeazabal (2003) para estimar el efecto del terrorismo en el PIB per cápita (<strong>gdpcap</strong>) en el País Vasco usando el método de control sintético. Los autores consideran como periodo pre intervención a 1955 - 1969.</p>
<ol style="list-style-type: lower-alpha">
<li><p>[10 puntos] Estime el control sintético del PIB per cápit del País Vasco usando como <em>grupo donador</em> al resto de las regiones de España. Esto es, encuentre la matriz <span class="math inline">\(W\)</span> que otorga pesos a las distintas regiones usando una serie de predictores observables. Para este propósito, use como predictores el promedio de las siguientes variables para el periodo 1964-1969:</p>
<ul>
<li>La inversión como porcentaje del PIB, <strong>invest</strong></li>
<li>El porcentaje de la población analfabeta, <strong>school.illit</strong></li>
<li>El porcentaje de la población con educación primaria, <strong>school.prim</strong></li>
<li>El porcentaje de la población con educación media, <strong>school.med</strong></li>
<li>El porcentaje de la población con educación superior, <strong>school.high</strong></li>
<li>El porcentaje de la población con educación más que superior, <strong>school.post.high</strong></li>
</ul>
<p>Además, use como <em>predictores especiales</em> los siguientes valores:</p>
<ul>
<li>El promedio del PIB per capita, <strong>gdpcap</strong>, de 1960 a 1969</li>
<li>La densidad de población, <strong>popdens</strong>, de 1969</li>
<li>El promedio de la participación de la agricultura, <strong>sec.agriculture</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la energía, <strong>sec.energy</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la industria, <strong>sec.industry</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de la construcción, <strong>sec.construction</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de los servicios, <strong>sec.services.venta</strong>, de 1961 a 1969</li>
<li>El promedio de la participación de los servicios no comerciables, <strong>sec.services.nonventa</strong>, de 1961 a 1969</li>
</ul>
<p>Note que el País Vasco está identificado con el número 17 de la variable <strong>regionno</strong>. Realice el procedimiento de optimización para minimizar las discrepancias entre la unidad tratada y su sintético usando el periodo 1960-1969.</p>
<p>¿Qué regiones y con qué pesos contribuyen a construir el País Vasco sintético?</p>
<p><em>Implementamos el método de control sintético:</em></p>
<pre class="r"><code>setwd(&quot;C:/Users/rojas/Dropbox/Evaluación de Programas Sociales/2021/tareas/Tarea 4&quot;)

data_vasco &lt;- data.frame(read_csv(&quot;./basque.csv&quot;))

dataprep.out &lt;- dataprep(foo = data_vasco,
                  predictors = c(&quot;invest&quot;, &quot;school.illit&quot;, &quot;school.prim&quot;, &quot;school.med&quot;, &quot;school.high&quot;, &quot;school.post.high&quot;),
                  predictors.op = c(&quot;mean&quot;),
                  dependent = c(&quot;gdpcap&quot;),
                  unit.variable = c(&quot;regionno&quot;),
                  time.variable = c(&quot;year&quot;),
                  special.predictors = list(
                    list(&quot;gdpcap&quot;, 1960:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.agriculture&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.energy&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.industry&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.construction&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.venta&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.nonventa&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;popdens&quot;, 1969,c(&quot;mean&quot;))),
                  treatment.identifier = 17,
                  controls.identifier = c(2:16,18),
                  time.predictors.prior = c(1964:1969),
                  time.optimize.ssr = c(1960:1969),
                  unit.names.variable = c(&quot;regionname&quot;),
                  time.plot = c(1955:1997))

synth.out &lt;- synth(data.prep.obj = dataprep.out)

synth.tables &lt;- synth.tab(
  dataprep.res = dataprep.out,
  synth.res = synth.out
)</code></pre>
<p><em>Recuperamos los pesos:</em></p>
<pre class="r"><code>print(synth.tables$tab.w)</code></pre>
<pre><code>##    w.weights                   unit.names unit.numbers
## 2      0.000                    Andalucia            2
## 3      0.000                       Aragon            3
## 4      0.000       Principado De Asturias            4
## 5      0.000             Baleares (Islas)            5
## 6      0.000                     Canarias            6
## 7      0.000                    Cantabria            7
## 8      0.000              Castilla Y Leon            8
## 9      0.000           Castilla-La Mancha            9
## 10     0.851                     Cataluna           10
## 11     0.000         Comunidad Valenciana           11
## 12     0.000                  Extremadura           12
## 13     0.000                      Galicia           13
## 14     0.149        Madrid (Comunidad De)           14
## 15     0.000           Murcia (Region de)           15
## 16     0.000 Navarra (Comunidad Foral De)           16
## 18     0.000                   Rioja (La)           18</code></pre>
<p><em>El País Vasco sintético se obtiene como una combinación de Cataluña y Madrid, con unos pesos de 0.851 y 0.149, respectivamente.</em></p></li>
<li><p>[10 puntos] Obtenga un gráfico en donde represente las series de tiempo del PIB per cápita del País Vasco que efectivamente se realizó, la de su correspondiente control sintético y la del promedio simple del resto de las regiones españolas. Esto es, coloque en un solo gráfico la información de las diapositivas 25 y 26 de la <a href="https://eps-2021.netlify.app/clases/clase_24.html#25">clase 25</a>.</p>
<p><em>Recuperamos las series originales y sintética del País Vasco:</em></p>
<pre class="r"><code>Ys &lt;- dataprep.out$Y0plot %*% synth.out$solution.w

Y1 &lt;- dataprep.out$Y1plot</code></pre>
<p>*Por otro lado, podemos calcular el promedio sobre todas las regiones de la matriz <span class="math inline">\(Y0plot\)</span>:</p>
<pre class="r"><code>Y0media &lt;- matrix(rowMeans(dataprep.out$Y0plot))</code></pre>
<p><em>Y ponemos todo en un data frame para graficarlo fácilmente:</em></p>
<pre class="r"><code>data.plot &lt;- as.data.frame(cbind(Y1,Ys, Y0media))

colnames(data.plot) &lt;- c(&quot;Y1&quot;,&quot;Ys&quot;,&quot;Y0media&quot;)
data.plot &lt;- data.plot %&gt;% 
  mutate(year=seq(from=1955, to=1997))

#Gráfico de series
data.plot %&gt;% 
  ggplot(aes(x=year))+
  geom_line(aes(y=Y1, linetype = &quot;País Vasco&quot;)) +
  geom_line(aes(y=Ys, linetype = &quot;Sintético&quot;))+
  geom_line(aes(y=Y0media, linetype = &quot;Resto de España&quot;))+
  geom_vline(xintercept=1970, color = &quot;black&quot;, size=1, linetype=&quot;dashed&quot;)+
  scale_x_continuous(breaks=seq(1955, 1997, 5))+
   labs(x = &quot;Año&quot;,
    y = &quot;PIB per capita&quot;,
    linetype = &quot;Legend&quot;) +
  scale_linetype_manual(values = c(&quot;País Vasco&quot;=&quot;solid&quot;, &quot;Sintético&quot;=&quot;dashed&quot;, &quot;Resto de España&quot;=&quot;dotted&quot;))</code></pre>
<p><img src="/tareas/tarea_4/tarea4_respuestas_files/figure-html/unnamed-chunk-6-1.png" width="672" />
<em>El País Vasco era más rico que el promedio del resto de las regiones españolas. Durante el periodo post al inicio de la actividad terrorista, el resto de España siguió creciendo, pero el País Vasco se acercó hacia abajo.</em></p></li>
<li><p>[10 puntos] Genere una gráfica de brechas que muestre el efecto del terrorismo sobre el PIB per capita. La brecha es la diferencia entre la serie de tiempo realizada y su contraparte sintética.</p>
<p><em>El gráfico de brechas se obtiene fácilmente con las funciones de Synth:</em></p>
<pre class="r"><code>gaps.plot(synth.res = synth.out,
      dataprep.res = dataprep.out,
      tr.intake = 1970,
      Ylab = c(&quot;GDP per capita&quot;),
      Xlab = c(&quot;year&quot;), 
      Ylim = c(-4,4))</code></pre>
<p><img src="/tareas/tarea_4/tarea4_respuestas_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><em>El gráfico de las trayectorias es:</em></p>
<p><img src="/tareas/tarea_4/tarea4_respuestas_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p></li>
<li><p>[10] Realice un ejercicio de placebos en el espacio, similar al que llevamos a cabo en el laboratorio. La idea es estimar el control sintético para todas las regiones. Una vez que tenga el PIB per capita sintético para las 17 regiones, genere un histograma donde represente la razón del error de predicción cuadrado medio. Para ello, para cada región, debe obtener el error de predicción cuadrado promedio para los periodos pre y post intervención y luego obtener la razón de estos. ¿Cómo es la razón del error de predicción cuadrado medio para el País Vasco y qué nos dice de la significancia estadística del efecto estimado?</p>
<p><em>Noten que la región 1 es el total de España. No queremos usar esa región, así que el loop debe ignorarla. El ejercicio placebo es:</em></p>
<pre class="r"><code>placebos &lt;- data.frame(matrix(ncol = 17, nrow = 43))

#Hacemos un ciclo para operacionalizar el trabajo
for (j in 2:18) {

tunit &lt;- j
tunit_m1 &lt;- j-1
tunit_p1 &lt;- j+1

if (j==2)
  dpool &lt;- c(3:18)
else
  if (j==18)
dpool &lt;- c(2:17)
  else
dpool &lt;- c(2:tunit_m1,tunit_p1:18)

dataprep.out &lt;- dataprep(foo = data_vasco,
                  predictors = c(&quot;invest&quot;, &quot;school.illit&quot;, &quot;school.prim&quot;, &quot;school.med&quot;, &quot;school.high&quot;, &quot;school.post.high&quot;),
                  predictors.op = c(&quot;mean&quot;),
                  dependent = c(&quot;gdpcap&quot;),
                  unit.variable = c(&quot;regionno&quot;),
                  time.variable = c(&quot;year&quot;),
                  special.predictors = list(
                    list(&quot;gdpcap&quot;, 1960:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.agriculture&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.energy&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.industry&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.construction&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.venta&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;sec.services.nonventa&quot;, 1961:1969,c(&quot;mean&quot;)),
                    list(&quot;popdens&quot;, 1969,c(&quot;mean&quot;))),
                  treatment.identifier = j,
                  controls.identifier = dpool,
                  time.predictors.prior = c(1964:1969),
                  time.optimize.ssr = c(1960:1969),
                  unit.names.variable = c(&quot;regionname&quot;),
                  time.plot = c(1955:1997))

#Repetimos tareas
synth.out &lt;- synth(data.prep.obj = dataprep.out)
Ys &lt;- dataprep.out$Y0plot %*% synth.out$solution.w
Y1 &lt;- dataprep.out$Y1plot

data.plot &lt;- as.data.frame(cbind(Y1,Ys))
colnames(data.plot) &lt;- c(&quot;Y1&quot;,&quot;Ys&quot;)
data.plot &lt;- data.plot %&gt;% 
  mutate(gap=Y1-Ys)

#Guardamos donde corresponde
placebos[,j-1] &lt;- data.plot$gap

#Para ir viendo en dónde vamos
print(j)

}


##Ahora tenemos un panel de regiones placebo
placebos &lt;- placebos %&gt;% 
  mutate(year=seq(from=1955, to=1997))

#Pasamos todo a formato long
placebos &lt;- placebos %&gt;%
  pivot_longer(cols=starts_with(&quot;X&quot;),
           names_to = &quot;region&quot;,
           values_to = &quot;gdp_synth&quot;) %&gt;% 
  mutate(region=as.numeric(substr(region,2,3))) %&gt;% 
  mutate(region=region+1) %&gt;% 
  mutate(treated=ifelse(region==17,1,0)) %&gt;% 
  mutate(treated=factor(treated, levels=c(&quot;0&quot;,&quot;1&quot;), labels=c(&quot;regiones de control&quot;, &quot;País Vasco&quot;)))</code></pre>
<p><em>No era necesario replicar este gráfico, pero lo hacemos para visualizar qué esperar:</em></p>
<pre class="r"><code>placebos %&gt;%
  ggplot(aes(x=year, y=gdp_synth, group=region, linetype=treated, color=treated))+
  geom_line()+
  scale_linetype_manual(values=c(&quot;solid&quot;, &quot;solid&quot;))+
  scale_color_manual(values=c(&quot;grey&quot;,&quot;black&quot;)) +
  ylab(&quot;PIB per cápita&quot;)+
  xlab(&quot;Año&quot;)+
  geom_vline(xintercept=1970, color = &quot;black&quot;, size=.5, linetype=&quot;dashed&quot;)+
  geom_hline(yintercept=0, color = &quot;black&quot;, size=.5, linetype=&quot;dashed&quot;)+
  scale_x_continuous(breaks=seq(1955, 1997, 5))+
  theme(legend.title = element_blank(),
    legend.position = c(.14, .90),
    legend.box.background = element_rect(color=&quot;black&quot;, size=.3),
    legend.box.margin = margin(1, 1, 1, 1))</code></pre>
<p><img src="/tareas/tarea_4/tarea4_respuestas_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><em>La mayoría de las regiones tienen buen ajuste pre intervención y la brecha post intervención del País Vasco efectivamente parece atípica. Calculemos el error cuadrático de predicción promedio pre y post intervención:</em></p>
<pre class="r"><code>mspe &lt;- placebos %&gt;% 
  mutate(pre = ifelse(year&lt;1970,&quot;pre&quot;,&quot;post&quot;),
         spe = gdp_synth^2) %&gt;% 
  group_by(region, pre) %&gt;% 
  summarise(mspe = mean(spe)) %&gt;% 
  ungroup() %&gt;%
  pivot_wider(id_cols = region,
              names_from = pre,
              values_from = mspe) %&gt;%
  mutate(ratio_mspe=post/pre) %&gt;% 
  mutate(tipo = ifelse(region==17, &quot;País Vasco&quot;, &quot;Otras regiones&quot;))</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;region&#39;. You can override using the `.groups` argument.</code></pre>
<p><em>Y hago un histograma:</em></p>
<pre class="r"><code>mspe %&gt;% 
  ggplot(aes(ratio_mspe, fill=tipo)) +
  geom_histogram(binwidth  = 20)</code></pre>
<p><img src="/tareas/tarea_4/tarea4_respuestas_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><em>El País Vasco resulta tener la sexta razón de MSPE más grande. Mi interpretación es la siguiente: hay regiones que crecieron debido a cambios estructurales en su economía ocurridas en algún momento posterior a 1970. Cataluña debe ser un típico ejemplo. Entonces, el MSPE post 1970 está capturando las discrepancias entre el sintético que proyecta lo que hubiera pasado si no hubiera habido estos cambios y lo que efectivamente sucedió a estas regiones, que no tiene que ver con el terrorismo.</em></p>
<p><em>Recuerden que el placebo asume que nada pasa en el resto de las unidades. La lección que sacamos de esto es que tengamos cuidado con los placebos en el espacio cuando es posible que las unidades del grupo donador sufran cambios pos intervención, no relacionadas a la intervención.</em></p></li>
</ol>
</div>
<div id="pregunta-2" class="section level1">
<h1>Pregunta 2</h1>
<p>Basado en Low, H., y Meghir, C. (2017).<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li><p>[5 puntos] ¿Cuáles son las diferencias entre un modelo econométrico estructural y uno de forma reducida?</p>
<p><em>Algunas diferencias incluyen:</em></p>
<ol style="list-style-type: decimal">
<li><p><em>Los modelos estructurales tienen como primitivas las funciones de utilidad, beneficios y/o pagos de los agentes económicos.</em></p></li>
<li><p><em>Los modelos de forma reducida no describen los canales por los cuales ocurren los efectos de un cambio en las variables independientes. En cambio, los modelos estructurales son útiles para trazar los canales por medio de los cuales los agentes responden a cambios en las variables relevantes y, potencialmente, incorporan la endogeneidad de las variables de estado.</em></p></li>
<li><p><em>Los modelos de forma reducida no capturan del todo la dinámica de los efectos. Los modelos estructurales incorporan el aspecto dinámico de muchas decisiones económicas, por ejemplo, incorporando cómo las decisiones presentes afectan la utilidad futura (por ejemplo, al invertir en capital humano). Los modelos estructurales también pueden incorporar incertidumbre al incluir la formación de expectativas que afecta las decisiones en el presente. Finalmente, los modelos estructurales también son útiles para incorporar la interacción estratégica de los agentes.</em></p></li>
</ol></li>
<li><p>[5 puntos] ¿Qué se entiende por un modelo completamente especificado?</p>
<p><em>Un modelo complemente especificado expone explícitamente:</em></p>
<ol style="list-style-type: decimal">
<li><em>La forma funcional de las primitivas</em></li>
<li><em>El conjunto de opciones sobre el que los agentes optimizan</em></li>
<li><em>Las funciones de política/decisión/reacción que definen cómo los agentes deciden con respecto al valor de las variables de estado</em></li>
<li><em>Las funciones de transición de las variables de estado</em></li>
<li><em>La función valor del problema</em></li>
</ol></li>
<li><p>[5 puntos] ¿Cómo se puede combinar la información proveniente de una intervención experimental con un modelo estructural? Mencione un ejemplo de una combinación exitosa de esta naturaleza.</p>
<p><em>La variación experimental puede ser empleada para estimar el modelo estructural y para validarlo.</em></p>
<p><em>En cuanto a la estimación, la variación exógena, por ejemplo, en Attanasio, Meghir y Santiago (2012), se emplea para identificar la respuesta de los agentes a distintos niveles de la transferencia de PROGRESA (la transferencia varía por sexo y por nivel educativo). La posibilidad de usar la variación exógena en la estimación es limitada dado que muchas veces las intervenciones se manifiestan como variables binarias.</em></p>
<p><em>Por otro lado, se puede usar la variación exógena para validar los modelos estructurales. Por ejemplo, usando los datos del grupo de control, se pueden estimar los parámetros en el modelo. Luego se puede usar el modelo para obtener la respuesta esperada a un cambio exógeno en el ingreso (en este caso, PROSPERA) y validar hipótesis</em></p></li>
<li><p>[5 puntos] ¿En qué consiste el método de momentos para la estimación de modelos estructurales?</p>
<p><em>El método de momentos es un método para la estimación de modelos estructurales. La idea es definir momentos muestrales que se desean replicar con el modelo. Por ejemplo, la media y varianza de la deserción en un modelo de asistencia escolar, o ciertos cuartiles en la distribución de años de escolaridad acumulados. La estimación del modelo consiste en encontrar los parámetros que son consistentes con las condiciones de optimización y que mejor aproximen los momentos muestrales seleccionados.</em></p></li>
</ol>
</div>
<div id="pregunta-3" class="section level1">
<h1>Pregunta 3</h1>
<p>Basado en Athey e Imbens (2019).<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li><p>[5 puntos] ¿Cuál es la diferencia entre machine learning y los modelos econométricos estándar?</p>
<p><em>La diferencia principal se encuentra en el propósito de la estimación. Con los modelos econométricos tradicionales buscamos los parámetros que rigen la relación entre variables. Consideramos estos parámetros de central importancia para la comprensión de fenómenos económicos. En cambio, las técnicas de machine learning tienen como objetivo primordial la predicción y los modelos se juzgan con base en este criterio. Los parámetros estimados frecuentemente se conocen como pesos, quitando de ellos la connotación de fundamentales para la comprensión de las relaciones económicas.</em></p></li>
<li><p>[5 puntos] ¿Para qué sirven y en qué consisten las técnicas LASSO y de regresión ridge?</p>
<p><em>LASSO y ridge son técnicas de machine learning para la selección de modelos. Aunque el objetivo principal es la predicción, se prefieren también modelos parsimoniosos a modelos más complicados. Por tanto, los diversos algoritmos empleados para generar predicciones castigan modelos más complejos. Además, cuando se trabaja con datos grandes, frecuentemente se tienen características que no tienen ninguna relación con la variable de interés, sin embargo, es difícil decir cuáles son por simple inspección. Los algoritmos de LASSO y ridge sirven para realizar esta tarea de seleccionar las características empleadas para la predicción penalizando modelos más complejos.</em></p></li>
<li><p>[5 puntos] ¿En qué consisten los árboles de regresión y los bosques aleatorios?</p>
<p><em>Los árboles de regresión son técnicas para hacer predicciones. En cada nodo del árbol se elige una característica y un nivel crítico de la misma que define una variable binaria. Para cada unidad, las dos ramas pueden llevar a una predicción o a una nueva partición usando una nueva variable. Los bosques aleatorios son técnicas que permiten refinar las predicciones de los árboles de regresión. Los bosques se generan a partir de muestras bootstrap con las que se estiman los árboles de regresión, usando subconjuntos de características.</em></p></li>
<li><p>[5 puntos] ¿Cómo puede emplearse machine learning para la estimación de efectos de tratamiento?</p>
<p><em>Machine learning puede ser auxiliar en distintas técnicas de estimación de efectos de tratamiento. Por ejemplo, pueden usarse para estimar el propensity score y condicionar a que el modelo resultante balancee las características. En el contexto de control sintético, puede emplearse para seleccionar las características que se usan para estimar el control sintético y para seleccionar los individuos del grupo donador que aportan información para construirlo. La disponibilidad de datos grandes permite analizar efectos heterogéneos de los tratamientos, que pueden ser identificados usando técnicas de machine learning.</em></p></li>
</ol>
</div>
<div id="pregunta-4" class="section level1">
<h1>Pregunta 4</h1>
<p>Basado en Varían (2014).<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<ol style="list-style-type: lower-alpha">
<li><p>[5 puntos] ¿Qué es la predicción fuera de la muestra?</p>
<p><em>La predicción fuera de la muestra se refiere a la capacidad de los modelos estimados a partir de ciertos datos para predecir con unos nuevos datos no usados para la estimación.</em></p></li>
<li><p>[5 puntos] ¿A qué se refiere el problema de sobreajuste en la predicción?</p>
<p><em>Se refiere a que al usar un conjunto de datos para estimar y juzgar el desempeño del modelo con base en qué tan bien el modelo replica los mismos datos es poco informativo sobre la capacidad predictiva del modelo fuera de la muestra.</em></p></li>
<li><p>[5 puntos] ¿Cómo se puede evaluar el efecto de una campaña de publicidad en internet empleando las técnicas descritas en el texto?</p>
<p><em>Una propuesta presentada en el texto consiste en recabar datos sobre usuarios y sus patrones de gasto y actividad en la red previo a la introducción de la campaña. Con estos datos, entrenar un modelo de predicción de ventas que tome en cuenta la estacionalidad y otros factores que las afectan. Luego, una vez arrancada la campaña publicitaria, comparar los valores predichos de ventas con los valores realizados y juzgar como efecto del tratamiento a la diferencia entre estas dos cantidades.</em></p></li>
<li><p>[5 puntos] ¿Cuál es la principal fuente de incertidumbre en el modelo en el contexto de big data?</p>
<p><em>La principal fuente de incertidumbre se convierte en la elección del modelo. Esto se había reconocido de cierta manera en la econometría tradicional en forma de “pruebas de robustez”. Las técnicas de machine learning han adoptado el promedio de modelos, lo cual rara vez ocurre en la econometría más tradicional, como una forma de tomar en cuenta de manera explícita la incertidumbre sobre los modelos para la predicción.</em></p></li>
</ol>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Low, H., &amp; Meghir, C. (2017). The use of structural models in econometrics. <em>Journal of Economic Perspectives</em>, 31(2), 33-58.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Athey, S., &amp; Imbens, G. W. (2019). Machine learning methods that economists should know about. <em>Annual Review of Economics</em>, 11.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Varian, H. R. (2014). Big data: New tricks for econometrics. <em>Journal of Economic Perspectives</em>, 28(2), 3-28<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
